### ISSUE TITLE
Cache not working

### ISSUE THREAD

**Issue by anjossilva** [Azure-Samples/active-directory-dotnet-native-desktop#13]
I start the app, authenticate, all it's good, and the cache stores the token in the file.
But everytime I restart the app, although the cache has the token, the authentication process mandates me to insert the credentials again.
Wasn't it supposed to be a Single visual login process?

**Comment by dstrockis** [comment]
Thanks for posting in GH.  Did you change the sample code at all?  Upon restart, at which point does the app ask you to login again? After you click the 'Sign In' button?
