### ISSUE TITLE
Not able to sign in successfully as it throws error/exception.

### ISSUE THREAD

**Issue by shayazm** [Azure-Samples/active-directory-dotnet-native-desktop#15]
![image](https://cloud.githubusercontent.com/assets/24910527/23328925/1c604714-fb53-11e6-8e8f-2e760051a7f6.png)

It took one day to over come this problem but was in vain.
I have checked it many times and tried with some other tenant name but that too in vain.
Please give me a detailed solution so as to get it done in one go....
Thanks.

**Comment by shayazm** [comment]
Got it working by **# removing tenant name** from below lines in app.config and web.config respectively:

In **## app.config** change,
from :  <add key="todo:TodoListResourceId" value="https://<tenant_name>/TodoListService" />
to     :  <add key="todo:TodoListResourceId" value="https://TodoListService" `/>

In ## **web.config** change,
from :  <add key="ida:Audience" value="https://<tenant_name>/TodoListService" />
to     :  <add key="ida:Audience" value="https://TodoListService" />

**Comment by shayazm** [comment]
Got it working by # **removing tenant name** from below lines in app.config and web.config respectively:

In **app.config** change,
from : `<add key="todo:TodoListResourceId" value="https://<teanant_name>/TodoListService" />`
to : `<add key="todo:TodoListResourceId" value="https://TodoListService" />`

In **web.config** change,
from : `<add key="ida:Audience" value="https://<teanant_name>/TodoListService" />`
to : `<add key="ida:Audience" value="https://TodoListService" />`

**Comment by gsacavdm** [comment]
Hey @shayazm, apologies for the confusion and extra overhead, there was an issue in the readme, the instructions should've guided you to register an app that indeed had the "https://\<tenant_name\>/TodoListService" AppID Uri and thus would work by simply doing the replacement.
