### ISSUE TITLE
Use AcquireTokenSilent rather than PromptBehavior.Never

### ISSUE THREAD

**Issue by danieldobalian** [Azure-Samples/active-directory-dotnet-native-desktop#16]
The client app does acquireToken using PromptBehavior.Never. It may be preferable to use acquireTokenSilent as we do in on behalf of cases.  

Current: attempts silent token acquisition using acquireToken w/ a PromptBehavior.
Proposed: attempt silent token acquisition using acquireTokenSilent.

**Comment by jmprieur** [comment]
Done
