### ISSUE TITLE
Is there a way to delete ESTSAUTHPERSISTENT cookies in this type of app?

### ISSUE THREAD

**Issue by shueybubbles** [Azure-Samples/active-directory-dotnet-native-desktop#27]
We've found that ADAL won't force a password prompt when logging in with an MSA, ie a user that has been imported into the tenant, if the user had previously entered the password, regardless of whether our process has restarted since then. We want to force a password prompt for all accounts on initial login during each process lifetime. This sample would be a good place to add that code...

**Comment by kalyankrishna1** [comment]
Please use the [PromptBehavior ](https://msdn.microsoft.com/en-us/library/azure/microsoft.identitymodel.clients.activedirectory.promptbehavior.aspx) enum to control this behavior.
