### ISSUE TITLE
Token validation parameters are being ignored

### ISSUE THREAD

**Issue by FcrNah** [Azure-Samples/active-directory-dotnet-native-desktop#28]
I've successfully configured service app in azure and everything works fine.

But it seems like it never really validates token claims against AuthenticationOptions.

For example, I'm still able to call API if i put validation parameters like this:
```
app.UseWindowsAzureActiveDirectoryBearerAuthentication(
	new WindowsAzureActiveDirectoryBearerAuthenticationOptions
	{
		Tenant = "google.com",
		TokenValidationParameters = new TokenValidationParameters
		{
			ValidAudience = "dummy"
		}
	});
```

**Comment by jmprieur** [comment]
Closing this issue as we are archiving this sample
