### ISSUE TITLE
MFA not working via Conditional Policy

### ISSUE THREAD

**Issue by gouthamb** [Azure-Samples/active-directory-dotnet-native-desktop#33]
Hi, I was able to successfully configure the desktop app.

I'm trying to enforce MFA for users accessing the application. I have configured a conditional Access Policy for ALL USERS accessing the RESOURCE SERVER from ALL CLIENT APPS but The user is not prompted for MFA during Sign-in. 

When I Enforce MFA on a user-level however, the user is prompted for MFA. Please let me know if I'm missing something or if this desktop app supports MFA via Conditional Access.

Thanks in advance!

**Comment by jmprieur** [comment]
@danieldobalian : who could help here?

**Comment by kalyankrishna1** [comment]
It might be a cached access token , sign-out and sign-in again.
Change the policy to target "all users " to "Resource app" and try again please.

**Comment by jmprieur** [comment]
Closing this issue as we are archiving this sample
